### ISSUE TITLE
"docker exec -ti nginx ngxproxy" 's issues

### ISSUE THREAD

**Issue by kfengc27** [mondediefr/docker-flarum#10]
Hi guys, when I install Flarum this afternoon, I try to  setup proxy by running this command:  **"docker exec -ti nginx ngxproxy"** . But the terminal ask me enter **Certificate path** without stop. Looks like this 👇 
![image](https://cloud.githubusercontent.com/assets/7607884/25794993/9f80e56c-3416-11e7-93a6-cc79b930194d.png)

I tried server times, but all happens like this. : (

And the configure file in my docker-composer.yml is  like this : 

```
flarum:
  image: mondedie/docker-flarum:0.1.0-beta.6-stable
  container_name: flarum
  links:
    - mariadb:mariadb
  environment:
    - FORUM_URL=https://www.ueec10.com
    - DB_PASS=hello123
  volumes:
    - /mnt/docker/flarum/assets:/flarum/app/assets
    - /mnt/docker/flarum/extensions:/flarum/app/extensions

mariadb:
  image: mariadb:10.1
  container_name: mariadb
  volumes:
    - /mnt/docker/mysql/db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=hello123
    - MYSQL_DATABASE=flarum
    - MYSQL_USER=flarum
    - MYSQL_PASSWORD=hello123


nginx:
  image: wonderfall/boring-nginx
  container_name: nginx
  links:
    - flarum:flarum
  ports:
    - "80:8000"
    - "443:4430"
  volumes:
    - /mnt/docker/nginx/sites-enabled:/sites-enabled
    - /mnt/docker/nginx/conf:/conf.d
    - /mnt/docker/nginx/log:/var/log/nginx
    - /mnt/docker/nginx/certs:/certs
```

Hope your reply, how to enter " Certificate key path" after "Certificate key path" :)
