### ISSUE TITLE
 ERROR: Couldn't find env file: /mnt/docker/flarum/flarum.env

### ISSUE THREAD

**Issue by InVinCiblezz** [mondediefr/docker-flarum#100]
I have pulled flarum image and created the Docker-compose.yml.

When I was running docker-compose,

ERROR: Couldn't find env file: /mnt/docker/flarum/flarum.env

How should I fix this problem? 
Thank you!

**Comment by Hydrog3n** [comment]
Hello @InVinCiblezz Did you well create the env file ?

**Comment by LittleSheep2010** [comment]
You can try this docker-compose.yml:

```yaml
version: "3"

services:
  flarum:
    image: mondedie/flarum:stable
    container_name: flarum_core
    environment:
      - DEBUG=false
      - FORUM_URL=http://forum.smartsheep.club
      - DB_HOST=mariadb
      - DB_NAME=flarum
      - DB_USER=flarum
      - DB_PASS=blablabla
      - DB_PREF=flarum_
      - DB_PORT=3306
      - FLARUM_ADMIN_USER=blablabla
      - FLARUM_ADMIN_PASS=blablabla
      - FLARUM_ADMIN_MAIL=cadenjiang@outlook.com
      - FLARUM_TITLE=SmartSheep Studio
    volumes:
      - /root/dt-applications/flarum/assets:/flarum/app/public/assets
      - /root/dt-applications/flarum/extensions:/flarum/app/extensions
      - /root/dt-applications/flarum/storage/logs:/flarum/app/storage/logs
      - /root/dt-applications/flarum/nginx:/etc/nginx/flarum
    ports:
      - 8888:8888
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    container_name: flarum_mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=blablabla
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=blablabla
    volumes:
      - /root/dt-applications/flarum/mysql:/var/lib/mysql
```
