### ISSUE TITLE
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve [SOLVED]

### ISSUE THREAD

**Issue by talesam** [mondediefr/docker-flarum#106]
I can't do the installation, the first one that doesn't load the variables that are in the .env I have to type everything on the web, in the first installation, and when I apply this error in the title appears.

I put information from the container log below:

```
[INFO] Setting folder permissions
[INFO] First launch, installation...
Installing Flarum...
Connecting to database...failed
Rolling back...
In Pipeline.php line 85:
               
  Step failed  
               
In Exception.php line 18:
                                                                               
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name d  
  oes not resolve                                                              
                                                                               
In PDOConnection.php line 40:
                                                                               
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name d  
  oes not resolve                                                              
                                                                               
In PDOConnection.php line 40:
                                                                               
  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name does  
   not resolve                                                                 
                                                                               
install [-f|--file FILE] [-c|--config CONFIG]
[INFO] End of flarum installation
[INFO] End of startup script. Forum is starting.

```
![Screenshot_20220225_002014](https://user-images.githubusercontent.com/981368/155647591-c63ee94b-cf66-433c-bc38-e7216e45568c.png)

**Comment by Magicalex** [comment]
Your mysql host is wrong. Use mariadb host.

**Comment by 368573607** [comment]
> Your mysql host is wrong. Use mariadb host.

I used mariadb. But catched the same error.

**Comment by talesam** [comment]
> 

use my file as an example, remembering that the variables are in a separate .env.

```
version: "3.9"

services:
  forum_db:
    image: mariadb:10.5
    container_name: forum_db
    environment:
      - MYSQL_ROOT_PASSWORD=YOUPASSWORDROOT
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=YOUPASSWORD
    volumes:
      - ./forum/mysql/db:/var/lib/mysql
    networks:
      forum-net:

  flarum:
    image: mondedie/flarum:stable
    container_name: flarum
    env_file:
      - .env
    volumes:
      - ./forum/assets:/flarum/app/public/assets
      - ./forum/extensions:/flarum/app/extensions
      - ./forum/storage/logs:/flarum/app/storage/logs
      - ./forum/nginx:/etc/nginx/flarum
    expose:
      - "8888"
    depends_on:
      - forum_db
    networks:
      forum-net:

networks:
  forum-net:
      name: forum-net
      ```
