### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by Bjornskjald** [mondediefr/docker-flarum#18]
```
Something went wrong: <!DOCTYPE html> <html> <head lang="en"> <meta charset="UTF-8"> <title></title> </head> <body> <h1>500 Internal Server Error</h1> <p>Something went wrong on our server.</p> </body> </html>
```

`docker logs flarum`:

```
[INFO] First launch, you must install flarum by opening your browser and setting database parameters.
```

`docker exec -ti flarum tail -f /tmp/ngx_error.log`:

*nothing appears*

`docker exec -ti flarum tail -f /tmp/php_error.log`:

```
[29-Jan-2018 22:02:08] NOTICE: fpm is running, pid 12
[29-Jan-2018 22:02:08] NOTICE: ready to handle connections
```

**Comment by Bjornskjald** [comment]
So nothing really interesting appears in every log, but it still somehow crashes (?)

**Comment by hardware** [comment]
Switch DEBUG environment variable to true to see the error message.

**Comment by Bjornskjald** [comment]
I found this: `SQLSTATE[HY000] [2002] No such file or directory`
May this be the problem?

**Comment by hardware** [comment]
> May this be the problem?

Yes. Your database seems to not be in a good state. Your have a connect error using PDO. Try to recreate your database container and rename your volume :

```
docker-compose stop mariadb
docker-compose rm mariadb
mv /mnt/docker/mysql /mnt/docker/mysql.bak
```

Can you give me your docker-compose.yml file content and MariaDB logs ?

**Comment by Bjornskjald** [comment]
```
 ⚡ root@bjorn  ~/docker-flarum  cat docker-compose.yml
flarum:
  image: mondedie/docker-flarum:0.1.0-beta.7.1-stable
  container_name: flarum
  links:
    - mariadb:mariadb
  ports:
    - "8888:8888"
  environment:
    - FORUM_URL=https://forum.domain.tld
    - DB_PASS=flarum
    - UID=nginx
    - GID=nginx
    - DEBUG=true
  volumes:
    - /mnt/docker/flarum/assets:/flarum/app/assets
    - /mnt/docker/flarum/extensions:/flarum/app/extensions

mariadb:
  image: mariadb:10.1
  container_name: mariadb
  volumes:
    - /mnt/docker/mysql/db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=flarum
    - MYSQL_DATABASE=flarum
    - MYSQL_USER=flarum
    - MYSQL_PASSWORD=flarum
```

**Comment by Bjornskjald** [comment]
MariaDB logs: https://pastebin.com/JMB29wAy

**Comment by hardware** [comment]
I can't reproduce your error with a fresh install. Any idea @Hydrog3n @Magicalex ?

Does your database work with another service ?

Here my local docker-compose file, if it can help you :

```yml
version: "3"

services:
  traefik:
    image: traefik:1.5-alpine
    container_name: traefik
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml:ro

  flarum:
    image: mondedie/docker-flarum:0.1.0-beta.7.1-stable
    container_name: flarum
    labels:
      - traefik.enable=true
      - traefik.backend.port=8888
      - traefik.frontend.rule=Host:flarum.local
    environment:
      - FORUM_URL=http://flarum.local
      - DB_PASS=123456
    volumes:
      - /mnt/docker/flarum/assets:/flarum/app/assets
      - /mnt/docker/flarum/extensions:/flarum/app/extensions
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.1
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=123456
    volumes:
      - /mnt/docker/mysql/db:/var/lib/mysql
```

And my `traefik.toml` :

```toml
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "local"
watch = true
exposedbydefault = false
```
