### ISSUE TITLE
Upgrade of container results in lost database config

### ISSUE THREAD

**Issue by Braintelligence** [mondediefr/docker-flarum#20]
I'm running this container in rancher. I upgraded the container and changed a label by doing so (to increase php upload limit) which resulted in loss of database config.
It's as if the environment variables for database settings do nothing at all.

When trying to enter the old database settings I get this with DEBUG=true:
![grafik](https://user-images.githubusercontent.com/6761196/38752418-638eb0d8-3f5b-11e8-8e54-3cc72fa71955.png)

What should I do so the container keeps the database settings?

This is my docker-compose:

```yaml
version: '2'

volumes:
  flarum-vol:
    driver: local
  flarum-mariadb-vol:
    driver: local
    
services:
  flarum:
    image: mondedie/docker-flarum:0.1.0-beta.7.1-stable
    container_name: flarum
    ports:
      - 8888
    labels:
      rap.le_email: XXXXXXX
      rap.port: '8888'
      io.rancher.scheduler.affinity:host_label: XXXXX=XXXXX
      rap.le_host: XXXXXXX
      rap.client_max_body_size: 150M
      io.rancher.container.pull_image: always
      rap.host: XXXXXXXX
    environment:
      - FORUM_URL=https://XXXXXXX
      - DB_PASS=XXXXXXX
      - DB_USER=flarum
      - DB_PREF=flarum_
      - DB_HOST=mariadb
    volumes:
      - flarum-vol:/flarum/app/
    links:
      - mariadb

  mariadb:
    image: mariadb:10.1
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=XXXXXXXXX
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=XXXXXXX
    volumes:
      - flarum-mariadb-vol:/var/lib/mysql
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: XXXXXX=XXXXXX
```

**Comment by hardware** [comment]
Flarum container volumes are not properly defined, you must use two differents volumes, one for extensions and another for assets. Like this :

```yml
volumes:
  - xxx:/flarum/app/assets
  - xxx:/flarum/app/extensions
```

It's not a good idea to store `/flarum/app/` entire directory with a named docker volume.

Did you lose data in `/flarum/app/assets` directory ? Check if `rev-manifest.json` exist. If not, create it manually because the boot script use this file to know if an installation has already been performed.

https://github.com/mondediefr/docker-flarum/blob/990087f809350528a1260f610b5876bbb744604c/rootfs/usr/local/bin/run.sh#L57-L58

**Comment by Braintelligence** [comment]
Thank you for clarifying. I wanted to not create two separate volumes, since volume-subfolders are not supported yet ☹️. Well, looks like I have to do it then.
Actually even restarting removed the config.php. Gonna try using two volumes now.

**Comment by hardware** [comment]
You can create two named volumes with rancher :

```yml
volumes:
  flarum-assets-vol:
    driver: local
  flarum-extensions-vol:
    driver: local

services:
  flarum:
    volumes:
      - flarum-assets-vol:/flarum/app/assets
      - flarum-extensions-vol:/flarum/app/extensions
```
