### ISSUE TITLE
Can't install flarum

### ISSUE THREAD

**Issue by Jvlythical** [mondediefr/docker-flarum#4]
When I click the install flarum button, I keep getting an internal error. I entered mariadb as the MySQL host, flarum as the database and the username and test123 as the password. Is there any way I can get the logs of the server? My docker version is 1.11.1 and the only output I get from the flarum container is: 

```
flarum     | [INFO] First launch, you must install flarum by opening your browser and setting database parameters.
```

Docker-composle.yml:

```
flarum:
  image: mondedie/docker-flarum
  container_name: flarum
  links:
    - mariadb:mariadb
  environment:
    - FORUM_URL=http://76.105.7.45:3991
    - DB_PASS=test123
    - DEBUG=true
  volumes:
    - /mnt/docker/flarum/assets:/flarum/app/assets
    - /mnt/docker/flarum/extensions:/flarum/app/extensions

#- /mnt/docker/flarum/config.php:/flarum/app/config.php

mariadb:
  image: mariadb:10.1
  container_name: mariadb
  volumes:
    - /mnt/docker/mysql/db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=test123
    - MYSQL_DATABASE=flarum
    - MYSQL_USER=flarum
    - MYSQL_PASSWORD=test123

nginx:
  image: wonderfall/boring-nginx
  container_name: nginx
  links:
    - flarum:flarum
  ports:
    - "3991:8000"
    - "443:4430"
  volumes:
    - /mnt/docker/nginx/sites-enabled:/sites-enabled
    - /mnt/docker/nginx/conf:/conf.d
    - /mnt/docker/nginx/log:/var/log/nginx
    - /mnt/docker/nginx/certs:/certs
```

**Comment by hardware** [comment]
`docker exec -ti flarum tail -f /tmp/ngx_error.log`

**Comment by Magicalex** [comment]
The password must contain at least 8 characters.

**Comment by renyuneyun** [comment]
Hi, I'm having perhaps the same issue, although a different docker-compose.yml file is used (slightly modified according to the example).

The docker-compose.yml file I use is:
```
flarum:
  image: mondedie/docker-flarum
  container_name: flarum
  links:
    - mariadb:mariadb
  ports:
    - "80:8888"
  environment:
    - FORUM_URL=http://127.0.0.1
    - DB_PASS='dbflarum'
  volumes:
    - /mnt/docker/flarum/assets:/flarum/app/assets
    - /mnt/docker/flarum/extensions:/flarum/app/extensions

mariadb:
  image: mariadb:10.1
  container_name: mariadb
  volumes:
    - /mnt/docker/mysql/db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD='rootdbpwd'
    - MYSQL_DATABASE=flarum
    - MYSQL_USER=flarum
    - MYSQL_PASSWORD='dbflarum'
```

The logs in /tmp/ngx_error.log are just repeating:
`2016/12/18 21:50:37 [error] 14#14: *5 FastCGI sent in stderr: "PHP message: PHP Deprecated:  The third argument to Zend\Stratigility\MiddlewarePipe() ($out) will be required starting with Stratigility version 2; please see https://docs.zendframework.com/zend-stratigility/migration/to-v2/ for more details on how to update your application to remove this message. in /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php on line 101" while reading response header from upstream, client: 172.17.0.1, server: , request: "POST / HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "127.0.0.1", referrer: "http://127.0.0.1/"`

**Comment by Jvlythical** [comment]
I got that same error as well and after some searching I think the image might have to be re-built? According to this discussion, https://discuss.flarum.org/d/636-help-me-set-up-my-conf-file/30, some got the same error and it was recommended to "try re-downloading the beta – I think we applied a hotfix very shortly after the initial release which fixed this error."

**Comment by hardware** [comment]
I have rebuild this image yesterday, but flarum version is freeze, so fix and update will came in the next version. 

Zend deprecated message is already fixed but not available in beta 6 : https://github.com/flarum/core/issues/1065

 Can you try with a real domain in `FORUM_URL` ?

**Comment by hardware** [comment]
Deprecated message fixed in https://github.com/mondediefr/docker-flarum/commit/d37bf950a628e0d8e916035d22eb7dc653a9c503.

**Comment by renyuneyun** [comment]
I can confirm my problem is due to wrong database settings:
The creation step of the database used null password (for root), but I stopped it and re-run everything using the config above. Then I tried to fill in the installation page of flarum, the error appears.
(I can confirm this because I executed `mysql -u root` in the mariadb container, successfully logged in and looked at the `mysql.user` table.)

After removeing everything from /mnt/docker/mysql and re-run the container, everything is fine.

p.s. There is nothing in `/flarum/app/storage/logs`, which is a bit surprising.

**Comment by webeindustry** [comment]
I can't get this to install. I've tried on different os, & by manually compiling image. The furthest I can get is to the web installer page, but it always says a 500 error, yet logs show nothing.

[https://i.imgur.com/myMaZWh.png
![mymazwh](https://cloud.githubusercontent.com/assets/9564369/21462032/2a4b377a-c91d-11e6-8945-e23c9d9d826b.png)
](url)

**Comment by Magicalex** [comment]
Indeed, mysql host is the name of your container mysql/mariadb

**Comment by renyuneyun** [comment]
Yes, everything is ok for me now.

**Comment by webeindustry** [comment]
Image works well. Trying to tweak it for webless installs.

**Comment by webeindustry** [comment]
I got the web-free installs working 😸

**Comment by jadsonlourenco** [comment]
I'm getting this error, I've put all info correctly, but not install:
`
Something went wrong: <!DOCTYPE html> <html> <head lang="en"> <meta charset="UTF-8"> <title></title> </head> <body> <h1>500 Internal Server Error</h1> <p>Something went wrong on our server.</p> </body> </html>
`

**Comment by Magicalex** [comment]
Can you show me your docker-compose.yml file?

**Comment by jadsonlourenco** [comment]
ok: 
```
version: '3'
services:
  flarum:
    image: mondedie/docker-flarum
    container_name: flarum
    ports:
      - "8888:8888"
    environment:
      - FORUM_URL=http://127.0.0.1      
      - DB_PASS=test
      - DEBUG=true    
    links:
      - mariadb:mariadb

  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"    
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=test
```

**Comment by jadsonlourenco** [comment]
The database and mysql user is working fine, I can connect using other client, but I can't install.
The installation page don't have validation on the form?

Thank you

**Comment by Magicalex** [comment]
All is ok for me with your docker-compose file.
Config:
![](https://images.mondedie.fr/VEg8TAqZ/8Sfd53PB.png)

**Comment by jadsonlourenco** [comment]
Can be the Docker version? I'm using Docker on Mac, I will try on Linux now, moment

**Comment by Magicalex** [comment]
```
$ docker -v
Docker version 1.13.0, build 49bf474
```
On mac os v10.12.2

**Comment by jadsonlourenco** [comment]
Docker version 1.13.1-rc1, build 2527cfc - MacOS 10.12.3

**Comment by jadsonlourenco** [comment]
Nop, same error on Linux, http://dejavuclub.tk/ is the same info of dockerfile

**Comment by jadsonlourenco** [comment]
Ops, works, did you test and make it work? Now are installed, can be because of the site url param?

**Comment by Magicalex** [comment]
It works. I complete your form. You need to valide form

**Comment by jadsonlourenco** [comment]
How? What is wrong, the admin password is so easy?

**Comment by jadsonlourenco** [comment]
Yes, the error is because of the user password, need have more than 8 characters, but don't show any error about... But thank you so much for the help. :heart:

**Comment by Magicalex** [comment]
I reused password in your docker-compose.
So see this https://github.com/mondediefr/docker-flarum#screenshot
You need to click on "install flarum" at the end

**Comment by mpgn** [comment]
I have the same problem : 

![image](https://cloud.githubusercontent.com/assets/5891788/25345251/e07839d8-2914-11e7-94b3-3de22664e772.png)


My conf file : 

```
flarum:
  image: mondedie/docker-flarum:0.1.0-beta.6-stable
  container_name: flarum
  links:
    - mariadb:mariadb
  environment:
    - FORUM_URL=https://discuss.domain.fr
    - DB_PASS=AtEQ8832q7xWmyM
  volumes:
    - /mnt/docker/flarum/assets:/flarum/app/assets
    - /mnt/docker/flarum/extensions:/flarum/app/extensions

mariadb:
  image: mariadb:10.1
  container_name: mariadb
  volumes:
    - /mnt/docker/mysql/db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=AtEQ8832q7xWmyM
    - MYSQL_DATABASE=flarum
    - MYSQL_USER=flarum
    - MYSQL_PASSWORD=AtEQ8832q7xWmyM
```

Also, what is the diff between  `MYSQL_PASSWORD` and `DB_PASS` ?
