### ISSUE TITLE
Make exposed port configurable

### ISSUE THREAD

**Issue by Technowix** [mondediefr/docker-flarum#5]
For being able to have multiple flarum behind a proxy, I can't see any solution but this :| maybe i'm wrong ?

**Comment by Magicalex** [comment]
You need to change url of proxy_pass
```nginx
location / {
  proxy_pass http://flarum-two:8888;
  include /conf.d/proxy-params.conf;
}
```

In your docker compose

```yml
flarum-two:
  image: mondedie/docker-flarum
  container_name: flarum-two
  environment:
    - DEBUG=true
    - ...
  volumes:
    - ...
```
