### ISSUE TITLE
Docker Compose build problem

### ISSUE THREAD

**Issue by 0ctave** [mondediefr/docker-flarum#53]
Hey guys ! I'm trying to run this image on my docker, so followed the README, but I keep getting 

`ERROR: manifest for mondedie/flarum:stable not found: manifest unknown: manifest unknown`

My docker-compose.yml is as follows

```
version: "3"

services:
  flarum:
    image: mondedie/flarum:stable
    container_name: flarum
    env_file:
      - ./flarum/flarum.env
    volumes:
      - ./flarum/assets:/flarum/app/public/assets
      - ./flarum/extensions:/flarum/app/extensions
      - ./flarum/nginx:/etc/nginx/conf.d
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dzqdzqdzq
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=qzdqdqdzqd
    volumes:
      - /mnt/docker/mysql/db:/var/lib/mysql
```
Thx for your help 😄
