### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by 0ctave** [mondediefr/docker-flarum#55]
I followed the README for the install and everything seems to work fine

```
flarum        | [INFO] First launch, installation...
flarum        | Installing Flarum...
flarum        | Connecting to database...done
flarum        | Writing config file...done
flarum        | Running migrations...done
flarum        | Writing default settings...done
flarum        | Creating admin user admin...done
flarum        | Publishing all assets...done
flarum        | Enabling bundled extensions...done
flarum        | DONE.
flarum        | [INFO] End of flarum installation
```

But I used Nginx Proxy Manager for my reverse proxy, and by pointing on the 8888 it only gives me à 502 Bad Gateway from Nginx. Does someone have an idea from where it migth come from ?

**Comment by Magicalex** [comment]
Nope, I need more information. config, log etc

**Comment by 0ctave** [comment]
The config is pretty basic, I just rebased the directories

```
  flarum:
    image: mondedie/flarum:latest
    container_name: flarum
    env_file:
      - ./flarum/flarum.env
    volumes:
      - ./flarum/assets:/flarum/app/public/assets
      - ./flarum/extensions:/flarum/app/extensions
      - ./flarum/nginx:/etc/nginx/conf.d
    depends_on:
      - db
```

But my folder doesn't seem go have any files from flarum except some fonts in the assets (but I guess they are on the docker container), aren't the files supposed to be downloaded in the volumes ?
