### ISSUE TITLE
Always getting the "Something went wrong" screen after setup

### ISSUE THREAD

**Issue by Christilut** [mondediefr/docker-flarum#58]
See the site [here](https://forums.mylittlesky.net/)

This is my .env
```
DEBUG=true
FORUM_URL=https://forums.mylittlesky.net
LOG_TO_STDOUT=true

# Database configuration
DB_HOST=mariadb
DB_NAME=flarum
DB_USER=flarum
DB_PASS=flarum_password_here
DB_PREF=flarum_
DB_PORT=3306

# User admin flarum (environment variable for first installation)
# /!\ admin password must contain at least 8 characters /!\
FLARUM_ADMIN_USER=admin
FLARUM_ADMIN_PASS=passwordhere
FLARUM_ADMIN_MAIL=me@example.com
FLARUM_TITLE=Crate Hackers Forum
```

And docker-compose:
```
version: "3"

services:
  flarum:
    image: mondedie/flarum:stable
    container_name: flarum
    env_file:
      - /database/docker/flarum/flarum.env
    volumes:
      - /database/docker/flarum/assets:/flarum/app/public/assets
      - /database/docker/flarum/extensions:/flarum/app/extensions
      - /database/docker/flarum/nginx:/etc/nginx/conf.d
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=flarum_password_here
    volumes:
      - /database/docker/mysql/db:/var/lib/mysql
```

I don't run Nginx on my system, but Caddy so I'm not sure what the `/etc/nginx/conf.d` volume is for, or is that maybe the problem?

Also I'm not sure how I can see more debug logging. I've enabled both DEBUG and LOG_TO_STDOUT but I don't see any extra logs.
