### ISSUE TITLE
Add way to persist composer auth

### ISSUE THREAD

**Issue by Hona** [mondediefr/docker-flarum#75]
I am trying to setup premium extiverse subscriptions:
![image](https://user-images.githubusercontent.com/10430890/111027696-9bff3f80-843d-11eb-90eb-25da5753e3fd.png)

For the first step I created the file `composer.repositories.txt` and added the line:
```
extiverse_premium|"repositories": [{"type": "composer", "url": "https://extiverse.com/composer/"}]
```

For the second step - I can attach to the container and run the command but it doesn't persist between container runs, am I missing something or does a file need to be mounted to the host to persist?

**Comment by Hydrog3n** [comment]
Hello, thank you for your issue. Can you paste the run command or the docker-compose you use? To see if it's normal or not, and maybe add this feature.

**Comment by Hona** [comment]
Hi, thanks for your response. 

I kept the Docker compose file pretty close to what is in the readme, I just used local directories instead of full paths for the volumes.

```yml
version: "3"

services:
  flarum:
    image: mondedie/flarum:stable
    container_name: flarum
    env_file:
      - ./flarum.env
    volumes:
      - ./flarum/assets:/flarum/app/public/assets
      - ./flarum/extensions:/flarum/app/extensions
      - ./flarum/nginx:/etc/nginx/flarum
    ports:
      - 8500:8888
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=redacted
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=redacted
    volumes:
      - ./mysql/db:/var/lib/mysql
```
