### ISSUE TITLE
Error 500 Installation Flarum

### ISSUE THREAD

**Issue by mpgn** [mondediefr/docker-flarum#9]
I have error 500 when i tried to install Flarum : 

![image](https://cloud.githubusercontent.com/assets/5891788/25345251/e07839d8-2914-11e7-94b3-3de22664e772.png)

My conf file : 

```
flarum:
  image: mondedie/docker-flarum:0.1.0-beta.6-stable
  container_name: flarum
  links:
    - mariadb:mariadb
  environment:
    - FORUM_URL=https://discuss.domain.fr
    - DB_PASS=AtEQ8832q7xWmyM
  volumes:
    - /mnt/docker/flarum/assets:/flarum/app/assets
    - /mnt/docker/flarum/extensions:/flarum/app/extensions

mariadb:
  image: mariadb:10.1
  container_name: mariadb
  volumes:
    - /mnt/docker/mysql/db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=AtEQ8832q7xWmyM
    - MYSQL_DATABASE=flarum
    - MYSQL_USER=flarum
    - MYSQL_PASSWORD=AtEQ8832q7xWmyM
```

docker ps
```
root@vps284653:~# docker ps
CONTAINER ID        IMAGE                                        COMMAND                  CREATED             STATUS              PORTS               NAMES
5075fab18ed5        mondedie/docker-flarum:0.1.0-beta.6-stable   "run.sh"                 7 minutes ago       Up 7 minutes        8888/tcp            flarum
8f68c0f40ed9        mariadb:10.1                                 "docker-entrypoint.sh"   7 minutes ago       Up 7 minutes        3306/tcp            mariadb
```

No information in `docker exec -ti flarum cat /tmp/ngx_error.log`

Nginx 
```
server {
    listen 80; listen [::]:80;
    server_name discuss.domain.fr;  # <-- change this

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;  listen [::]:443 ssl;
    server_name discuss.domain.fr;  # <-- change this

    ssl on;
    ssl_certificate /etc/nginx/ssl/public.pem;
    ssl_certificate_key /etc/nginx/ssl/private.pem;

    location / {
        proxy_pass http://172.17.0.3:8888;
        proxy_set_header Host $http_host;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

```

Une idée ?
